language: java

# explicit distribution specification
# to use xvfb as a service
dist: xenial

jdk: openjdk11

git:
  depth: false

services:
   - docker
   - xvfb

addons:
  sonarcloud:
    organization: "lorenzobettini-github"

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - mvn -f school-parent/pom.xml -Pjacoco clean verify sonar:sonar
